local Opts = {
	ensure_installed = {
		"bash",
		"c",
		"lua",
		"css",
		"dockerfile",
		"gitignore",
		"go",
		"gomod",
		"gosum",
		"gowork",
		"javascript",
		"json",
		"latex",
		"proto",
		"python",
		"rust",
		"scss",
		"solidity",
		"tsx",
		"typescript",
		"vim",
		"yaml",
		"html",
		"sql",
		"gitcommit",
		"make",
		"terraform",
		"toml",
	},
	sync_install = false,
	auto_install = true,
	highlight = {
		enable = true,
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "<C-space>",
			node_incremental = "<C-space>",
			scope_incremental = false,
			node_decremental = "<bs>",
		},
	},
}

return Opts